config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  path_names: {
    sign_in: 'login',
    sign_out: 'logout',
  },
  controllers: { 
    sessions: "users/sessions",
  }
  root 'pages#index'

  get '/about', to: 'pages#about'

  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]
  
  validates :name, :surname, :dob, :job_title, :hometown, :experience, presence: true
  validates :hometown, inclusion: { in: ['Baku', 'Moscow', 'London'] }
  validates :experience, inclusion: { in: ['1-3 years', '3-5 years', '5+ years'] }

  def full_name
    [name, surname].join(' ')
  end

  private
    def should_generate_new_friendly_id?
      slug.blank? || name_changed? || surname_changed? || job_title_changed?
    end
    def slug_candidates
    [
      [:name, :surname, :job_title]
    ]
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @employees = Employee.order(updated_at: :desc)
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_path(@employee), notice: 'Created successfully' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_path(@employee), notice: 'Updated successfully' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def employee_params
      params.require(:employee).permit(:name, :surname, :dob, :job_title, :hometown, :experience, :avatar)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Meta tags
  def title(str)
    content_for(:title, content = str.to_s)
  end

  def description(str)
    content_for(:description, content = str.to_s)
  end

  def og_image(str)
    content_for(:og_image, content = str.to_s)
  end
end

app/helpers/component_helper.rb
module ComponentHelper
  def component(name, data: {}, &block)
    render_component("components/#{name}", { data: data }, &block)
  end

  private

  def render_component(name, locals, &block)
    if block_given?
      render layout: name, locals: locals, &block
    else
      render partial: name, locals: locals
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def age(dob)
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/_form.html.slim
= simple_form_for(@employee, html: {multipart: true, class: 'uk-form-stacked'}) do |f|

  = f.input :name, wrapper_html: { class: 'uk-margin' }, label_html: { class: 'uk-form-label' }, input_html: { class: 'uk-input uk-border-rounded' }
  = f.input :surname, wrapper_html: { class: 'uk-margin' }, label_html: { class: 'uk-form-label' }, input_html: { class: 'uk-input uk-border-rounded' }
  = f.input :job_title, wrapper_html: { class: 'uk-margin' }, label_html: { class: 'uk-form-label' }, input_html: { class: 'uk-input uk-border-rounded' }
  = f.input :hometown, as: :select, collection: ['Baku', 'Moscow', 'London'], wrapper_html: { class: 'uk-margin' }, label_html: { class: 'uk-form-label' }, input_html: {class: 'uk-select uk-form-width-full uk-border-rounded'}
  = f.input :experience, as: :select, collection: ['1-3 years', '3-5 years', '5+ years'], wrapper_html: { class: 'uk-margin' }, label_html: { class: 'uk-form-label' }, input_html: {class: 'uk-select uk-form-width-full uk-border-rounded'}
  = f.input :dob, start_year: Date.today.year - 100, end_year: Date.today.year - 18, label: 'Date of Birth', wrapper_html: {class: 'uk-margin'}, label_html: { class: 'uk-form-label'}, input_html: {class: 'uk-select uk-form-width-small'} 
  
  .uk-margin
    div(uk-form-custom="target: true")
      = f.input_field :avatar
      input(class="uk-button uk-button-primary uk-border-rounded uk-button-small" type="text" placeholder="#{@employee.avatar.present? ? 'Change Avatar' : 'Select Avatar'}")

  = f.button :submit, class: 'uk-button-success uk-margin-right uk-border-rounded uk-button-small'
  = button_tag "Reset", type: :reset, class: 'uk-button uk-button-warning uk-border-rounded uk-button-small'

app/views/employees/edit.html.slim
- title 'Edit Employee'

section.uk-section.uk-section-default.uk-padding-remove-bottom
  .uk-container
    div.uk-grid-small(uk-grid)
      div(class="uk-width-1-2@m")
        ul.uk-breadcrumb
          li= link_to 'Home', root_path
          li= link_to 'Employees', employees_path
          li.uk-disabled
            a= content_for(:title)

      div(class="uk-width-1-2@m uk-text-right")
        = link_to employees_path, class: 'uk-button uk-button-danger uk-button-small uk-border-rounded' do
          span Cancel
          span.uk-margin-small-left(uk-icon="icon: ban; ratio: 0.8")


section.uk-section.uk-section-default.uk-section-small
  .uk-container
    div.uk-grid-small.uk-flex-center(uk-grid)
      div(class="uk-width-2-3@m")
        .uk-card.uk-card-primary.uk-border-rounded.uk-box-shadow-large
          .uk-card-body
            h2.uk-h4.uk-text-uppercase= content_for(:title)
            = render 'form'
            

app/views/employees/index.html.slim
- title t(".title")
- description t(".description")
- og_image image_url("cover.jpg")

section.uk-section.uk-section-default.uk-section-medium
  .uk-container
    div.uk-grid-small(uk-grid)
      div(class="uk-width-1-2@m")
        ul.uk-breadcrumb
          li= link_to 'Home', root_path
          li.uk-disabled
            a Employees

      div(class="uk-width-1-2@m uk-text-right")
        = link_to new_employee_path, class: 'uk-button uk-button-primary uk-button-small uk-border-rounded' do
          span Add Employee
          span.uk-margin-small-left(uk-icon="icon: plus-circle; ratio: 0.8")


    table.uk-table.uk-table-justify.uk-table-divider.uk-table-middle
      caption DATABASE
      thead
        tr
          th.uk-table-shrink Profile
          th Name
          th Surname
          th Age
          th Job Title
          th Hometown
          th Experience
      tbody
        - @employees.each do |employee|
          tr
            td= image_tag(employee.avatar.thumb.url, class: "uk-preserve-width uk-border-circle", style: 'width: 40px')
            td.uk-table-link= link_to employee.name, employee, class: 'uk-link-reset'
            td= employee.surname
            td= age(employee.dob)
            td= employee.job_title
            td= employee.hometown
            td= employee.experience

app/views/employees/new.html.slim
- title 'Add Employee'

section.uk-section.uk-section-default.uk-padding-remove-bottom
  .uk-container
    div.uk-grid-small(uk-grid)
      div(class="uk-width-1-2@m")
        ul.uk-breadcrumb
          li= link_to 'Home', root_path
          li= link_to 'Employees', employees_path
          li.uk-disabled
            a= content_for(:title)

      div(class="uk-width-1-2@m uk-text-right")
        = link_to employees_path, class: 'uk-button uk-button-danger uk-button-small uk-border-rounded' do
          span Cancel
          span.uk-margin-small-left(uk-icon="icon: ban; ratio: 0.8")


section.uk-section.uk-section-default.uk-section-small
  .uk-container
    div.uk-grid-small.uk-flex-center(uk-grid)
      div(class="uk-width-2-3@m")
        .uk-card.uk-card-primary.uk-border-rounded.uk-box-shadow-large
          .uk-card-body
            h2.uk-h4.uk-text-uppercase= content_for(:title)
            = render 'form'
            

app/views/employees/show.html.slim
- title t(".title", employee_name: @employee.name)
- description t(".description", employee_name: @employee.name)

section.uk-section.uk-section-default.uk-padding-remove-bottom
  .uk-container
    div.uk-grid-small(uk-grid)
      div(class="uk-width-1-2@m")
        ul.uk-breadcrumb
          li= link_to 'Home', root_path
          li= link_to 'Employees', employees_path
          li.uk-disabled
            a= @employee.full_name

      div(class="uk-width-1-2@m uk-text-right")
        = link_to edit_employee_path(@employee), class: 'uk-button uk-button-primary uk-button-small uk-border-rounded' do
          span Edit Employee
          span.uk-margin-small-left(uk-icon="icon: pencil; ratio: 0.8")

section.uk-section.uk-section-default.uk-section-small
  .uk-container
    div.uk-grid-small.uk-flex-center(uk-grid)
      div(class="uk-width-2-3@m")
        .uk-card.uk-card-primary.uk-border-rounded.uk-box-shadow-large
          .uk-card-header
            .uk-grid-small.uk-flex-middle uk-grid="" 
              .uk-width-auto= image_tag(@employee.avatar.thumb.url, class: "uk-border-pill uk-box-shadow-large", style: 'width: 80px')
              .uk-width-expand
                h3.uk-card-title.uk-margin-remove-bottom= @employee.full_name
                p.uk-text-meta.uk-margin-remove-top= @employee.job_title
          .uk-card-body
            p
              span.uk-label.uk-box-shadow-large Age
              span.uk-text-bold.uk-margin-left= age(@employee.dob)
            p
              span.uk-label.uk-box-shadow-large Hometown
              span.uk-text-bold.uk-margin-left= @employee.hometown
            p
              span.uk-label.uk-box-shadow-large Experience
              span.uk-text-bold.uk-margin-left= @employee.experience

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset='utf-8'
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    meta http-equiv='x-ua-compatible' content='ie=edge'
    meta[name='author' content='Azar Aliyev']
    meta[name='copyright' content='Azar Aliyev. Copyright (c) 2018']
    meta[name='description' content="#{ content_for(:description) }"]
    meta[property="og:image" content="#{ content_for(:og_image) }"]
    title= content_for(:title)
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
  body
    = render partial: "shared/flash_messages", flash: flash if !flash.empty?
    = component 'menu'
    = yield
    = javascript_include_tag 'application'

app/views/pages/about.html.slim
- title t(".title")
- description t(".description")
- og_image image_url("about.jpg")

= component 'cover', data: { title: 'About', subtitle: content_for(:description), cover: content_for(:og_image)}

app/views/pages/index.html.slim
- title t(".title")
- description t(".description")
- og_image image_url("cover.jpg")

= component 'cover'

app/views/shared/_flash_messages.html.slim
- flash.each do |type, message|
  = component 'alert', data: { type: type.to_sym, title: type.upcase, content: message, classes: 'uk-position-small uk-position-top uk-box-shadow-small uk-position-z-index' }